// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.code4schener.route.repository;

import org.code4schener.route.repository.LocationLogRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LocationLogRepository_Roo_Jpa_Repository {
    
    declare @type: LocationLogRepository: @Transactional(readOnly = true);
    
}
